apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capp-backend.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "capp-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwtSecretKey: {{ .Values.secret.jwtSecretKey | quote }}
  {{- range $i, $token := .Values.secret.clusterTokens }}
  clusterToken-{{ $i }}: {{ $token | quote }}
  {{- end }}
  {{- if .Values.secret.openshiftClientSecret }}
  openshiftClientSecret: {{ .Values.secret.openshiftClientSecret | quote }}
  {{- end }}
