{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "capp-backend.labels" . | nindent 4 }}
  {{- if (eq .Values.config.auth.mode "openshift") }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.capp-backend: {{ required "config.auth.openshift.redirectUri is required when config.auth.mode=openshift" .Values.config.auth.openshift.redirectUri | quote }}
  {{- end }}
{{- end }}
