{{- if and (eq .Values.config.auth.mode "openshift") .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "capp-backend.labels" . | nindent 4 }}
{{- end }}
