{{- if eq .Values.deployAs "deployment" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "capp-backend.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "capp-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "capp-backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.server.port }}
      protocol: TCP
{{- end }}
