version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - dupword
    - errcheck
    - errorlint
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - nestif
    - noctx
    - staticcheck
    - prealloc
    - revive
    - testifylint
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        path: test/e2e/*
      - linters:
          - dupl
        path: internal/*
      - linters:
            - dupl
        path: test/*
      - linters:
          - noctx
        path: _test\.go$
      - linters:
          - noctx
        path: internal/testutil/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$