apiVersion: v2
name: capp-backend
description: |
  Helm chart for the CAPP Backend — a secure API gateway that allows for the management of Capps.
version: 0.1.0
appVersion: "v0.1.0"
keywords:
  - capp
  - dana-team
  - kubernetes
  - api-gateway
home: https://github.com/dana-team/capp-backend
sources:
  - https://github.com/dana-team/capp-backend
maintainers:
  - name: dana-team
